baseurl = "http://www.lkjxblog.tech/"
theme = "nixon"
title = "Dawn Zeng's Blog"
languageCode = "en-us"
disqusShortname = "Xinta's Blog"
copyright = "Copyright (c) 2017, Dawn Zeng; all rights reserved."
MetaDataFormat = "yaml"

# used by Hugo shortcodes
#GoogleAnalytics = "UA-XXXXX-Y"

# note that the theme expects author both here and in the
# parameters section
[author]
    name = "Dawn Zeng"

# used by the theme
[indexes]
    tag = "tags"
    topic = "topics"

[params]
    notFoundHeader = """什么也没找到"""
	notFoundText = """出错啦，你访问的页面不存在哟～～～"""
	copyright_years = "2017"
	css_file = "/css/nixon.css"
	domain_name = "www.lkjxblog.tech"
	personal_site = "http://www.lkjxblog.tech/about/"

	[params.author]
		name = "Dawn Zeng"
		# The three quotes allow the biography to span
		# multiple lines. Must end with three, too.
#		short_bio = """ """

	[params.facebook]
		account = "fei.jianxin"
#	[params.feedburner]
#		account = "nixon.example"
	[params.github]
		account = "tokyo2006"
#	[params.googleplus]
#		account = ""
	[params.linkedin]
		account = "dawnzeng"
		source  = "https://www.linkedin.com/in/dawnzeng"
	[params.twitter]
		account = "rurounikexin"
#	[params.slideshare]
#		account = "nixon.example"

	[params.license]
		url = "http://www.lkjxblog.tech/license/"
		attribution = "all rights reserved"
