baseurl = "https://blog.lkjxblog.tech"
#theme = "nixon"
title = "曾晨的博客"
languageCode = "en-us"
disqusShortname = "曾晨的博客"
MetaDataFormat = "yaml"
hasCJKLanguage = true
# used by Hugo shortcodes
#GoogleAnalytics = "UA-XXXXX-Y"

# note that the theme expects author both here and in the
# parameters section
[author]
    name = "曾晨"

# used by the theme
[indexes]
    tag = "tags"
    topic = "topics"

[params]
    notFoundHeader = """什么也没找到"""
	notFoundText = """出错啦，你访问的页面不存在哟～～～"""
	css_file = "/css/nixon.css"
	domain_name = "blog.lkjxblog.tech"
	personal_site = "https://blog.lkjxblog.tech/about/"

	[params.author]
		name = "曾晨"
		# The three quotes allow the biography to span
		# multiple lines. Must end with three, too.
#		short_bio = """ """

	[params.facebook]
		account = "fei.jianxin"
#	[params.feedburner]
#		account = "nixon.example"
	[params.github]
		account = "tokyo2006"
#	[params.googleplus]
#		account = ""
	[params.linkedin]
		account = "dawnzeng"
		source  = "https://linkedin.com/in/dawnzeng"
	[params.twitter]
		account = "rurounikexin"
#	[params.slideshare]
#		account = "nixon.example"

	[params.license]
		url = "https://blog.lkjxblog.tech/license/"
		attribution = "all rights reserved"
