languageCode = "en-us"
title = "Xinta's Blog"
baseURL = "https://tokyo2006.github.io/"

disablePathToLower = false
pygmentsuseclasses = false
pygmentscodefences = false
pygmentsoptions = "linenos=true"
paginate = 6

[permalinks]
post = "/blog/:year-:month-:day-:title/"

[[menu.main]]
	Name = "首页"
	URL = "/"
	weight = -10

[[menu.main]]
	Name = "Java"
	URL = "/categories/java/"
	weight = -9

[[menu.main]]
	Name = "Linux"
	URL = "/categories/linux"
	weight = -8
[[menu.main]]
	Name = "关于"
	URL = "/about/"
	weight = 10

# Sidebar menus
# Enable with "sidebarMenuEnabled = true" in [params]
# Header text is "sidebarMenuHeader" in [params]


[[menu.sidebar]]
	Name = "首页"
	URL = "/"
	weight = 2
[indexes]
	tag = "tags"
	category = "categories"
[params]
    tableOfContents = false
	truncate = true
	comments = true
	author = "Xinta"
    subtitle = "梦里不知身是客"
    searchEngineURL = "https://www.google.com/search"
    continueReadingText = "想看更多内容吗"
    googleAnalytics = "google analytics"
    rss = true
    defaultDescription = "这是我重新记录博客的地方，免费并且开源，很棒！"
    defaultKeywords = ["java","sql","database","linux","devops","docker"]
	notFoundHeader = """什么也没找到"""
    notFoundText = "出错啦，你访问的页面不存在哟～～～"
	sidebarRecentLimit = 10
	sidebarHeader = "友情链接"
	sidebarText = """"""
	sidebarMenuEnabled = true
	sidebarMenuHeader = "Sidebar Links"
	github = "https://github.com/tokyo2006/"
	bitbucket = "https://bitbucket.org/tokyo2006/"
	twitter = "https://twitter.com/rurounikexin/"
	stackoverflow = ""
	linkedin = "https://www.linkedin.com/in/chen-zeng-5703205a/?trk=public-profile-join-page"
	facebook = "http://www.facebook.com/fei.jianxin"
	instagram = "http://www.instagram.com/tokyo2006/"
	disableReadingTime = false
	disableGoogleFonts = false
	generateTaxonomyList = true
[blackfriday]
	hrefTargetBlank = true 
	fractions = false

